name: Setup Firebase CLI
description: Install Firebase CLI

inputs:
  packager:
    description: The package manager used to install the CLI
    default: pnpm
  version:
    description: Version of Firebase CLI
    default: latest
  serviceAccountKey:
    description: Service account key to use
  projectId:
    description: Project id to use
  args:
    description: Additional arguments to pass to the CLI

runs:
  using: composite
  steps:
    - if: ${{ inputs.packager == 'pnpm' }}
      name: Install firebase-tools with pnpm
      shell: bash
      run: pnpm add -g firebase-tools@${{ inputs.version }}

    - if: ${{ inputs.packager == 'yarn' }}
      name: Install firebase-tools with pnpm
      shell: bash
      run: yarn global add firebase-tools@${{ inputs.version }}

    - if: ${{ inputs.packager == 'npm' }}
      name: Install firebase-tools with pnpm
      shell: bash
      run: npm install -g firebase-tools@${{ inputs.version }}

    - if: ${{ inputs.serviceAccountKey != '' }}
      name: Create service account key file
      shell: bash
      run: |
        echo '${{ inputs.serviceAccountKey }}' > ${{ runner.temp }}/serviceAccountKey.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(echo ${{ runner.temp }}/serviceAccountKey.json)" >> $GITHUB_ENV

    - if: ${{ inputs.projectId != '' }}
      name: Use firebase project
      shell: bash
      run: firebase use ${{ inputs.projectId }}

    - if: ${{ inputs.args != '' }}
      name: Launch firebase command with args
      shell: bash
      run: firebase ${{ inputs.args }}
