version = 0.1
[Dev.deploy.parameters]
stack_name = "kuzpot-dev"
resolve_s3 = true
s3_prefix = "kuzpot-dev"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
