name: Publish Mobile App Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "apps/mobile/**"
      - ".github/workflows/publish-mobile-preview.yml"

jobs:
  publish:
    name: Publish Mobile App Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install
        run: pnpm install

      - name: Publish preview
        run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          channel: pr-${{ github.event.number }}
